#include "core/base.h"
#include "core/config.h"
#include "core/debug.h"
#include "core/io.h"

#include "geom/line.h"
#include "geom/polygon.h"
#include "geom/rect.h"
#include "geom/vec2.h"

#include "graph/bipartite.h"
#include "graph/flow.h"
#include "graph/UD.h"
#include "graph/UU.h"
#include "graph/WD.h"
#include "graph/WU.h"

#include "math/fft.h"
#include "math/frac.h"
#include "math/linalge.h"
#include "math/linalgeGF2.h"
#include "math/linrec.h"
#include "math/mod.h"
#include "math/monoid.h"
#include "math/numtheory.h"

#include "str/ahocorasik.h"
#include "str/string.h"

#include "tree/dynseg.h"
#include "tree/dynseglazy.h"
#include "tree/fenwick.h"
#include "tree/hld.h"
#include "tree/linkcut.h"
#include "tree/pst.h"
#include "tree/pstlazy.h"
#include "tree/rooted.h"
#include "tree/seg.h"
#include "tree/seg2d.h"
#include "tree/segbu.h"
#include "tree/seglazy.h"
#include "tree/toptree.h"
#include "tree/treap.h"
#include "tree/treapBST.h"
#include "tree/trie.h"
#include "tree/unrooted.h"

#include "bucket.h"
#include "bucketbias.h"
#include "cumulQ.h"
#include "dpopt.h"
#include "functional.h"
#include "gccext.h"
#include "hashval.h"
#include "heapset.h"
#include "i128.h"
#include "list.h"
#include "monoQ.h"
#include "random.h"
#include "range.h"
#include "uf.h"
#include "zip.h"

signed main() {}
