#include "core/base.h"

#include "geom/line.h"
#include "geom/polygon.h"
#include "geom/rect.h"
#include "geom/vec2.h"

#include "graph/bipartite.h"
#include "graph/flow.h"
#include "graph/UD.h"
#include "graph/UU.h"
#include "graph/WD.h"
#include "graph/WU.h"

#include "math/fft.h"
#include "math/frac.h"
#include "math/linalge.h"
#include "math/linalgeGF2.h"
#include "math/linrec.h"
#include "math/mod.h"
#include "math/monoid2.h"
#include "math/numth/basic.h"
#include "math/numth/advance.h"
#include "math/numth/sieve.h"

#include "str/ahocorasik.h"
#include "str/string.h"

#include "tree/dynseg.h"
#include "tree/dynseglazy.h"
#include "tree/fenwick.h"
#include "tree/hld.h"
#include "tree/linkcut.h"
#include "tree/pst.h"
#include "tree/pstlazy.h"
#include "tree/rooted.h"
#include "tree/seg.h"
#include "tree/seg2d.h"
#include "tree/segbu.h"
#include "tree/seglazy.h"
#include "tree/toptree.h"
#include "tree/treap.h"
#include "tree/treapBST.h"
#include "tree/trie.h"
#include "tree/unrooted.h"

#include "misc/bucket.h"
#include "misc/bucketbias.h"
#include "misc/cumulQ.h"
#include "dp/dpopt.h"
#include "dp/slope.h"
#include "misc/functional.h"
#include "misc/gccext.h"
#include "misc/hashval.h"
#include "misc/heapset.h"
#include "misc/i128.h"
#include "misc/list.h"
#include "misc/monoQ.h"
#include "misc/random.h"
#include "misc/range.h"
#include "misc/uf.h"
#include "misc/zip.h"

signed main() {}
